### ISSUE TITLE
README references miscreant-go

### ISSUE THREAD

**Issue by derekcollison** [miscreant/miscreant-go#5]
However the repo is named miscreant.go.

We renamed the Go client for nats from go-nats to nats.go as well, but seeing some errors on `go get nats.go` that caused me to look here to see if you were having similar issues with naming.

**Comment by tarcieri** [comment]
Interesting, what problems are you encountering?

**Comment by derekcollison** [comment]
So if you do a `go get <project>.go` it will give an error but actually install correctly. Same with Go's listing tool as well. They have an issue opened but no plans to fix.

https://github.com/golang/go/issues/27096

**Comment by tarcieri** [comment]
Is this what I might've been doing differently?

```
$ go get github.com/miscreant/miscreant.go/
$ go get github.com/miscreant/miscreant.go
stat github.com/miscreant/miscreant.go: no such file or directory
```

**Comment by derekcollison** [comment]
Interesting.. Thanks..

**Comment by derekcollison** [comment]
Your README should change `miscreant-go` to `miscreant.go` still.
